<table class="table-employee" id="table-employee">
	<thead>
		<tr>
			<th class="table-employee-name">Name<div class="triangle-down" onclick="TDH.sortTable(true, false);"></div></th>
			<th>Telefon</th>
			<th class="table-employee-city">Ort<div class="triangle-down" onclick="TDH.sortTable(false, false);"></div></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><a href="#">Schlaffer, Willy</a></td>
			<td>07225 / 12345</td>
			<td>Gernsbach-Scheuern</td>
		</tr>
		<tr>
			<td><a href="#">Hartwigsen, Johannes</a></td>
			<td>07225 / 23456</td>
			<td>Mainz</td>
		</tr>
		<tr>
			<td><a href="#">Schwellung, Rosa</a></td>
			<td>07225 / 34567</td>
			<td>Rüsselsheim</td>
		</tr>
		<tr>
			<td><a href="#">Arbeit, Andi</a></td>
			<td>07225 / 45678</td>
			<td>Frankfurt a. M.</td>
		</tr>
		<tr>
			<td><a href="#">Hose, Kurt C.</a></td>
			<td>07225 / 56789</td>
			<td>Viernheim</td>
		</tr>
		<tr>
			<td><a href="#">Johanna, Marie</a></td>
			<td>07225 / 67890</td>
			<td>Bergisch Gladbach</td>
		</tr>
		<tr>
			<td><a href="#">Fährlich, Sergej</a></td>
			<td>07225 / 78901</td>
			<td>Bielefeld</td>
		</tr>
		<tr>
			<td><a href="#">Stein, Shawn</a></td>
			<td>07225 / 89012</td>
			<td>Brasilien</td>
		</tr>
		<tr>
			<td><a href="#">Panse, Jim</a></td>
			<td>07225 / 90123</td>
			<td>Frankfurt a. O.</td>
		</tr>
	</tbody>
</table>