<table class="tableEmployee" id="tableEmployee">
	<thead>
		<tr>
			<th class="table-employee-name">Name<div class="triangleDown" onclick="TDH.sortTable(true, false);"></div></th>
			<th>Telefon</th>
			<th class="table-employee-city">Ort<div class="triangleDown" onclick="TDH.sortTable(false, false);"></div></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><a href="#">Bayer, Renate</a></td>
			<td>07225 / 919214</td>
			<td>Gernsbach-Scheuern</td>
		</tr>
		<tr>
			<td><a href="#">König, Jessica</a></td>
			<td>07225 / 919214</td>
			<td>Mainz</td>
		</tr>
		<tr>
			<td><a href="#">Pelle, Melony</a></td>
			<td>07225 / 919214</td>
			<td>Rüsselsheim</td>
		</tr>
		<tr>
			<td><a href="#">Maurer, Sophie</a></td>
			<td>07225 / 919214</td>
			<td>Frankfurt a. M.</td>
		</tr>
		<tr>
			<td><a href="#">Furst, Martin</a></td>
			<td>07225 / 919214</td>
			<td>Viernheim</td>
		</tr>
		<tr>
			<td><a href="#">Roth, Sandra</a></td>
			<td>07225 / 919214</td>
			<td>Bergisch Gladbach</td>
		</tr>
		<tr>
			<td><a href="#">Ziegler, Kerstin</a></td>
			<td>07225 / 919214</td>
			<td>Bielefeld</td>
		</tr>
		<tr>
			<td><a href="#">Stein, Shawn</a></td>
			<td>07225 / 919214</td>
			<td>Brasilien</td>
		</tr>
		<tr>
			<td><a href="#">Panse, Jim</a></td>
			<td>07225 / 919214</td>
			<td>Frankfurt a. O.</td>
		</tr>
	</tbody>
</table>