<div class="pager">
    <ul>
        <li><a href="#" class="inactive">«</a></li>
        <li><a href="#" class="selected">1</a></li>
        <li><a href="ueberuns-sponsoren2.php">2</a></li>
        <li><a href="ueberuns-sponsoren3.php">3</a></li>
        <li><a href="#" class="inactive">4</a></li>
        <li><a href="#" class="inactive">5</a></li>
        <li><a href="ueberuns-sponsoren2.php">»</a></li>
    </ul>
</div>