<form method="post" class="table-sponsors-filter">
    <label for="letter">Tabelle filtern nach Anfangsbuchstabe</label>
    <select id="letter">
        <option>A</option>
        <option>B</option>
        <option>C</option>
        <option>D</option>
        <option>E</option>
        <option>F</option>
        <option>G</option>
        <option>H</option>
        <option>I</option>
        <option>J</option>
        <option>K</option>
        <option>L</option>
        <option>M</option>
        <option>N</option>
        <option>O</option>
        <option>P</option>
        <option>Q</option>
        <option>R</option>
        <option>T</option>
        <option>S</option>
        <option>U</option>
        <option>V</option>
        <option>W</option>
        <option>X</option>
        <option>Y</option>
        <option>Z</option>
    </select>
    
    <span>in</span>
    <input type="radio" name="filterChoice" id="filterChoiceName">
    <label for="filterChoiceName">Firmenname</label>
    <input type="radio" name="filterChoice" id="filterChoiceLocation">
    <label for="filterChoiceLocation">Ort</label>
    
    <input type="submit" value="filtern">
</form>