
<table class="table-sponsors">
	<thead>
		<tr>
			<th>Firmenlogo</th>
			<th>Name</th>
			<th>Ort</th>	
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
                <img src="images/pizza100x60.jpg" alt="Pizza">
			</td>
			<td><a href="#">Abacus Nachhilfeinstitut</a></td>
			<td>Gernsbach-Scheuern</td>
		</tr>
		<tr>
			<td>
                <img src="images/pizza100x60.jpg" alt="Pizza">
			</td>
			<td><a href="#">ABAKUS Computer</a></td>
			<td>Kuppenheim</td>
		</tr>
		<tr>
			<td>
                <img src="images/pizza100x60.jpg" alt="Pizza">
			</td>
			<td><a href="#">Adam Versicherungen</a></td>
			<td>Bischweiler</td>
		</tr>
		<tr>
			<td>
                <img src="images/pizza100x60.jpg" alt="Pizza">
			</td>
			<td><a href="#">Adolph Versicherungen</a></td>
			<td>Karlsruhe</td>
		</tr>
		<tr>
			<td>
                <img src="images/pizza100x60.jpg" alt="Pizza">
			</td>
			<td><a href="#">Adler Apotheke</a></td>
			<td>Kuppenheim</td>
		</tr>
		<tr>
			<td>
                <img src="images/pizza100x60.jpg" alt="Pizza">
			</td>
			<td><a href="#">Barmer, Krankenkasse</a></td>
			<td>Gaggenau</td>
		</tr>
	</tbody>
</table>