<!-- Modul: Navigation -->

<nav role="navigation" class="navigation">
	<!--Liste als Navigation, enthält pro Navigationselement einen Link mit anschliessender Liste
		des entsprechenden Untermenäs. Das Untermenü enthält eine Liste der entsprechenden Links.
	-->
  <ul>
    <li class="active"><a href="index.php">Start</a></li>
    <li><a href="veranstaltung.php">Veranstaltungen</a></li>
    <li><a href="ueberuns-dasteam.php">Über Uns</a></li>
    <li><a href="meldungen.php">Meldungen</a></li>
    <li><a href="helfen.php">Helfen</a></li>
    <li><a href="presse.php">Presse</a></li>
    <li><a href="kontakt.php">Kontakt</a></li>
  </ul>
</nav>  