<div>
    <ul>    
      <li><a href="#">2014</a></li>
      <li class="active"><a href="#">2013</a></li>
      <li><a href="#">2012</a></li>
      <li><a href="#">2011</a></li>
      <li><a href="#">2010</a></li>
      <li><a href="#">2009</a></li>
      <li><a href="#">2008</a></li>
      <li><a href="#">2007</a></li>
      <li><a href="#">2006</a></li>
      <li><a href="#">2005</a></li>
      <li><a href="#">2004</a></li>
      <li><a href="#">2003</a></li>
      <li><a href="#">2002</a></li>
      <li><a href="#">2001</a></li>
    </ul>
    <ul>
      <li><a href="#">Januar</a></li>
      <li><a href="#">Februar</a></li>
      <li><a href="#">März</a></li>
      <li><a href="#">April</a></li>
      <li><a href="#">Mai</a></li>
      <li><a href="#">Juni</a></li>
      <li><a href="#">Juli</a></li>
      <li><a href="#">August</a></li>
      <li><a href="#">September</a></li>
      <li><a href="#">Oktober</a></li>
      <li class="active"><a href="#">November</a></li>
      <li><a href="#">Dezember</a></li>
    </ul>
</div>