<h2>Unsere Aktivitäten</h2>
<div id="akkordeon" class="akkordeon">
    <article class="">
        <h3>Radbörse</h3>

        <div class="content">
            <p>
                Jemand musste Josef K. verleumdet haben, denn ohne
                dass er etwas Böses getan hätte, wurde er eines Morgens
                verhaftet. »Wie ein Hund! « sagte er, es war, als sollte
                die Scham ihn überleben. Als Gregor Samsa eines Morgens
                aus unruhigen Träumen erwachte, fand er sich in seinem
                Bett zu einem ungeheueren Ungeziefer verwandelt. Und
                <strong>strong</strong> es war ihnen wie eine
                Bestätigung ihrer neuen Träume und guten Absichten, als
                am Ziele ihrer Fahrt die Tochter als erste sich erhob
                und ihren jungen Körper dehnte. »Es ist ein
                eigentümlicher Apparat«, sagte der Offizier zu dem
                Forschungsreisenden und überblickte mit einem
                gewissermaßen bewundernden Blick den ihm doch
                <a class="external ext" href="#">link</a> wohlbekannten
                Apparat.
            </p>
            <ul>
                <li>
                    <h4>2009</h4>
                    <h5>Auch die 19. Radbörse war ein Riesenerfolg - rund 2.000 Besucher</h5>

                    <p>
                        Als Gregor Samsa eines Morgens
                        aus unruhigen Träumen erwachte, fand er sich in seinem
                        Bett zu einem ungeheueren Ungeziefer verwandelt. »Es ist ein
                        eigentümlicher Apparat«, sagte der Offizier zu dem
                        Forschungsreisenden und überblickte mit einem
                        gewissermaßen bewundernden Blick den ihm doch
                        wohlbekannten Apparat.
                        <a href="#">mehr...</a>
                    </p>
                </li>
                <li>
                    <h4>2008</h4>
                    <h5>1600 Euro Erlös bei der 18. Kuppenheimer Fahrradbörse</h5>
                </li>
                <li>
                    <h4>2006</h4>
                    <h5>Bestätigung ihrer neuen Träume und guten Absichten</h5>
                </li>
                <li>
                    <h4>2004</h4>
                    <h5>Immer wieder Sonntags kommt die Erinnerung</h5>
                </li>
                <li>
                    <h4>2003</h4>
                    <h5>Vom Himmel hoch da komm ich her!</h5>
                </li>
                <li>
                    <h4>2002</h4>
                    <h5>Aller Anfang ist schwer - auch ohne Viehzucht.</h5>
                </li>
            </ul>
        </div>
    </article>
    <article>
        <h3>Konzepte</h3>

        <div class="content">
            <p>
                Jemand musste Josef K. verleumdet haben, denn ohne
                dass er etwas Böses getan hätte, wurde er eines Morgens
                verhaftet. »Wie ein Hund! « sagte er, es war, als sollte
                die Scham ihn überleben. Als Gregor Samsa eines Morgens
                aus unruhigen Träumen erwachte, fand er sich in seinem
                Bett zu einem ungeheueren Ungeziefer verwandelt. Und
                <strong>strong</strong> es war ihnen wie eine
                Bestätigung ihrer neuen Träume und guten Absichten, als
                am Ziele ihrer Fahrt die Tochter als erste sich erhob
                und ihren jungen Körper dehnte. »Es ist ein
                eigentümlicher Apparat«, sagte der Offizier zu dem
                Forschungsreisenden und überblickte mit einem
                gewissermaßen bewundernden Blick den ihm doch
                <a class="external ext" href="#">link</a> wohlbekannten
                Apparat.
            </p>
            <ul>
                <li>
                    <h4>2009</h4>
                    <h5>Auch die 19. Radbörse war ein Riesenerfolg - rund 2.000 Besucher</h5>

                    <p>
                        Als Gregor Samsa eines Morgens
                        aus unruhigen Träumen erwachte, fand er sich in seinem
                        Bett zu einem ungeheueren Ungeziefer verwandelt. »Es ist ein
                        eigentümlicher Apparat«, sagte der Offizier zu dem
                        Forschungsreisenden und überblickte mit einem
                        gewissermaßen bewundernden Blick den ihm doch
                        wohlbekannten Apparat.
                        <a href="#">mehr...</a>
                    </p>
                </li>
                <li>
                    <h4>2008</h4>
                    <h5>1600 Euro Erlös bei der 18. Kuppenheimer Fahrradbörse</h5>
                </li>
                <li>
                    <h4>2006</h4>
                    <h5>Bestätigung ihrer neuen Träume und guten Absichten</h5>
                </li>
                <li>
                    <h4>2004</h4>
                    <h5>Immer wieder Sonntags kommt die Erinnerung</h5>
                </li>
                <li>
                    <h4>2003</h4>
                    <h5>Vom Himmel hoch da komm ich her!</h5>
                </li>
                <li>
                    <h4>2002</h4>
                    <h5>Aller Anfang ist schwer - auch ohne Viehzucht.</h5>
                </li>
            </ul>
        </div>
    </article>
    <article>
        <h3>Kinderfest</h3>

        <div class="content">
            <p>
                Jemand musste Josef K. verleumdet haben, denn ohne
                dass er etwas Böses getan hätte, wurde er eines Morgens
                verhaftet. »Wie ein Hund! « sagte er, es war, als sollte
                die Scham ihn überleben. Als Gregor Samsa eines Morgens
                aus unruhigen Träumen erwachte, fand er sich in seinem
                Bett zu einem ungeheueren Ungeziefer verwandelt. Und
                <strong>strong</strong> es war ihnen wie eine
                Bestätigung ihrer neuen Träume und guten Absichten, als
                am Ziele ihrer Fahrt die Tochter als erste sich erhob
                und ihren jungen Körper dehnte. »Es ist ein
                eigentümlicher Apparat«, sagte der Offizier zu dem
                Forschungsreisenden und überblickte mit einem
                gewissermaßen bewundernden Blick den ihm doch
                <a class="external ext" href="#">link</a> wohlbekannten
                Apparat.
            </p>
            <ul>
                <li>
                    <h4>2009</h4>
                    <h5>Auch die 19. Radbörse war ein Riesenerfolg - rund 2.000 Besucher</h5>

                    <p>
                        Als Gregor Samsa eines Morgens
                        aus unruhigen Träumen erwachte, fand er sich in seinem
                        Bett zu einem ungeheueren Ungeziefer verwandelt. »Es ist ein
                        eigentümlicher Apparat«, sagte der Offizier zu dem
                        Forschungsreisenden und überblickte mit einem
                        gewissermaßen bewundernden Blick den ihm doch
                        wohlbekannten Apparat.
                        <a href="#">mehr...</a>
                    </p>
                </li>
                <li>
                    <h4>2008</h4>
                    <h5>1600 Euro Erlös bei der 18. Kuppenheimer Fahrradbörse</h5>
                </li>
                <li>
                    <h4>2006</h4>
                    <h5>Bestätigung ihrer neuen Träume und guten Absichten</h5>
                </li>
                <li>
                    <h4>2004</h4>
                    <h5>Immer wieder Sonntags kommt die Erinnerung</h5>
                </li>
                <li>
                    <h4>2003</h4>
                    <h5>Vom Himmel hoch da komm ich her!</h5>
                </li>
                <li>
                    <h4>2002</h4>
                    <h5>Aller Anfang ist schwer - auch ohne Viehzucht.</h5>
                </li>
            </ul>
        </div>
    </article>
    <article>
        <h3>Basar</h3>

        <div class="content">
            <p>
                Jemand musste Josef K. verleumdet haben, denn ohne
                dass er etwas Böses getan hätte, wurde er eines Morgens
                verhaftet. »Wie ein Hund! « sagte er, es war, als sollte
                die Scham ihn überleben. Als Gregor Samsa eines Morgens
                aus unruhigen Träumen erwachte, fand er sich in seinem
                Bett zu einem ungeheueren Ungeziefer verwandelt. Und
                <strong>strong</strong> es war ihnen wie eine
                Bestätigung ihrer neuen Träume und guten Absichten, als
                am Ziele ihrer Fahrt die Tochter als erste sich erhob
                und ihren jungen Körper dehnte. »Es ist ein
                eigentümlicher Apparat«, sagte der Offizier zu dem
                Forschungsreisenden und überblickte mit einem
                gewissermaßen bewundernden Blick den ihm doch
                <a class="external ext" href="#">link</a> wohlbekannten
                Apparat.
            </p>
            <ul>
                <li>
                    <h4>2009</h4>
                    <h5>Auch die 19. Radbörse war ein Riesenerfolg - rund 2.000 Besucher</h5>

                    <p>
                        Als Gregor Samsa eines Morgens
                        aus unruhigen Träumen erwachte, fand er sich in seinem
                        Bett zu einem ungeheueren Ungeziefer verwandelt. »Es ist ein
                        eigentümlicher Apparat«, sagte der Offizier zu dem
                        Forschungsreisenden und überblickte mit einem
                        gewissermaßen bewundernden Blick den ihm doch
                        wohlbekannten Apparat.
                        <a href="#">mehr...</a>
                    </p>
                </li>
                <li>
                    <h4>2008</h4>
                    <h5>1600 Euro Erlös bei der 18. Kuppenheimer Fahrradbörse</h5>
                </li>
                <li>
                    <h4>2006</h4>
                    <h5>Bestätigung ihrer neuen Träume und guten Absichten</h5>
                </li>
                <li>
                    <h4>2004</h4>
                    <h5>Immer wieder Sonntags kommt die Erinnerung</h5>
                </li>
                <li>
                    <h4>2003</h4>
                    <h5>Vom Himmel hoch da komm ich her!</h5>
                </li>
                <li>
                    <h4>2002</h4>
                    <h5>Aller Anfang ist schwer - auch ohne Viehzucht.</h5>
                </li>
            </ul>
        </div>
    </article>
</div>