<!--Sponsorenliste-->
<link rel="stylesheet" href="../../css/tdh/modules/sponsorenliste.css">
<div class="sponsorliste">
  <span>Eine Auswahl unserer langj&aumlhrigen Sponsoren. Die vollst&aumlndige Liste unserer Sponsoren finden <a href="#">Sie hier.</a></span>
  <ul>
    <li><a href="#"><img src="../../images/sponsors/sponsor1.png" alt=""/></a></li>
    <li><a href="#"><img src="../../images/sponsors/sponsor2.png" alt=""/></a></li>
    <li><a href="#"><img src="../../images/sponsors/sponsor3.png" alt=""/></a></li>
    <li><a href="#"><img src="../../images/sponsors/sponsor4.png" alt=""/></a></li>
    <li><a href="#"><img src="../../images/sponsors/sponsor5.png" alt=""/></a></li>
  </ul>
</div>