
<div class="sponsorliste">
  <span>Eine Auswahl unserer langj&auml;hrigen Sponsoren. Die vollst&auml;ndige Liste unserer Sponsoren finden <a href="#">Sie hier.</a></span>
  <ul>
    <li><a href="https://www.spk-bbg.de/"><img src="../../images/sponsors/sponsor1.png" alt="Sponsorlogo - Sparkasse Baden-Baden Gaggenau"/></a></li>
    <li><a href="https://www.l-bank.de/"><img src="../../images/sponsors/sponsor2.png" alt="Sponsorlogo - L-Bank Staatsbank für Baden-W&uuml;rttenberg"/></a></li>
    <li><a href="http://www.radhaus-kastner.de/"><img src="../../images/sponsors/sponsor3.png" alt="Sponsorlogo - radhaus kastner"/></a></li>
    <li><a href="http://www.holzbau-hurrle.de/"><img src="../../images/sponsors/sponsor4.png" alt="Sponsorlogo - Holzbau Hurrle"/></a></li>
    <li><a href="https://www.volksbank-baden-baden-rastatt.de/"><img src="../../images/sponsors/sponsor5.png" alt="Sponsorlogo - Volksbank Baden-Baden &sdot; Rastatt eG"/></a></li>
  </ul>
</div>