<div class="content-widget-b">
    <h5>Das Team</h5>
    <div class="col33">
        <img src="images/team-beispielbild.jpg" alt="Unser Team"/>
    </div>
    <div class="col66">
        <p>
            Schreiben sie uns eine <a href="kontakt.php">Mail</a>
            oder rufen sie einen <a href="#">Mitarbeiter</a> an,
            wir informieren sie gerne persönlich.
        </p>
        <a href="ueberuns-dasteam.php">Hier finden sie eine Liste all unsrer aktiven Mitarbeiter</a>
    </div>
</div>