<div class="content-widget-b">
    <h5>Unsere Spendenkonten</h5>
    <div class="col50">
        <ul class="no-list">
            <li class="bold">Sparkasse</li>
            <li>Baden-Baden / Gaggenau</li>
            <li>
                <span class="bold indent">Konto-Nr.</span>
                <span>123 456</span>
            </li>
            <li>
                <span class="bold indent">BLZ</span>
                <span>987 654 321</span>
            </li>
        </ul>
    </div>
    <div class="col50">
        <ul class="no-list">
            <li><strong>Volksbank</strong></li>
            <li>Osnabrück</li>
            <li>
                <span class="bold indent">Konto-Nr.</span>
                <span>321 654 987</span>
            </li>
            <li>
                <span class="bold indent">BLZ</span>
                <span> 654 321</span>
            </li>
        </ul>
    </div>
</div>