<div class="content-widget-t">
    <span class="section-title">Vorgestellt</span>
    <h5>Franz Bürk - "Der Feuermacher"</h5>
    <img src="images/fackelmann.jpg" alt="Feuermacher"/>
    <p>
        Franz Bürk aus Achern - "der Feuermacher" - war eine große Bereicherung für das Kinderfest 2011,
        indem er jung und alt präsentierte, wie man man ohne technische Hilfsmittel Feuer erzeugen kann.
    <ul>
        <li><a href="#">Mehr in den Meldungen</a></li>
    </ul>
</div>